# Schema for the configuration files of the chat module.

uhsg_chat.config:
  type: config_object
  label: 'Chat configuration'
  mapping:
    display_chat_on_nodes:
      type: sequence
      label: 'List of node IDs where chat element should appear.'
      sequence:
        type: integer
        label: 'Value'
