<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uhsg_search_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $form['#attached']['library'][] = 'uhsg_search/uhsg-search';
  }
}

/**
 * Implements hook_views_pre_render().
 * Top content view has sitename in each result, remove that.
 */
function uhsg_search_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'google_analytics_summary' && $view->current_display == 'top_searches_block') {
    $sitename = \Drupal::config('system.site')->get('name');
    foreach ($view->result as &$result) {
      $result->pageTitle = str_replace(' | ' . $sitename, '', $result->pageTitle);
    }
  }
}
