<?php

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uhsg_search_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::service('path.matcher')->isFrontPage()) {
    $form['#attached']['library'][] = 'uhsg_search/uhsg-search';
  }
}

/**
 * Implements hook_preprocess_node().
 * Add content type as data attribute for search filtering.
 */
function uhsg_search_preprocess_node(&$variables) {
  if ($variables['view_mode'] == 'constrained') {
    $node = $variables['node'];
    if ($node->getType() == 'article') {
      $variables['attributes']['data-type'] = uhsg_search_article_is_degree_programme_specific($node) ? 'article_degree_programme_specific' : 'article_general';
    }
    else {
      $variables['attributes']['data-type'] = $node->getType();
    }
  }
}

/**
 * return TRUE if active degree programme is one of the terms in the node.
 *
 * @param $node
 */
function uhsg_search_article_is_degree_programme_specific($node) {
  $active_degree_programme = \Drupal::service('uhsg_active_degree_programme.active_degree_programme')->getId();
  $terms = $node->get('field_article_degree_programme')->getValue();
  if ($terms && $active_degree_programme) {
    foreach ($terms as $term) {
      // check if article has the active degree programme as term.
      if ($active_degree_programme == $term['target_id']) {
        return TRUE;
      }
    }
  }
  return FALSE;
}
