<?php

use Drupal\Core\Entity;

/**
 * @file
 * Install, update and uninstall functions for the student guide installation
 * profile.
 */

/**
 * Implements hook_install().
 *
 * Performs actions to set up the site for this profile.
 *
 * @see system_install()
 */
function student_guide_install() {
  // Disable the user pictures on nodes.
  \Drupal::configFactory()->getEditable('system.theme.global')->set('features.node_user_picture', FALSE)->save(TRUE);

  // Allow visitor account creation, but with administrative approval.
  \Drupal::configFactory()->getEditable('user.settings')->set('register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)->save(TRUE);
}

/**
 * Add path aliases (translations) for "/news".
 */
function student_guide_update_8001(&$sandbox) {
  $system_path = '/news';
  $path_aliases = ['fi' => '/uutiset', 'sv' => '/nyheter'];

  foreach ($path_aliases as $langcode => $path_alias) {
    \Drupal::service('path.alias_storage')->save($system_path, $path_alias, $langcode);
  }
}

/**
 * Move english login/logout links to main menu.
 * Delete other login/logout links.
 */
function student_guide_update_8002(&$sandbox) {
  $links = \Drupal::entityTypeManager()->getStorage('menu_link_content')->loadMultiple();

  $titles_to_delete = ['Kirjaudu sisään', 'Kirjaudu ulos', 'Logga in', 'Logga ut'];
  $titles_to_move = ['Login', 'Logout'];

  foreach ($links as $link) {
    if (in_array($link->getTitle(), $titles_to_delete)) {
      $link->delete();
    }
    if (in_array($link->getTitle(),  $titles_to_move)) {
      $link->set('menu_name', 'main');
      if ($link->getTitle() == 'Login') {
        $link->addTranslation('sv', ['title' => 'Logga in']);
        $link->addTranslation('fi', ['title' => 'Kirjaudu sisään']);
      }
      else {
        $link->addTranslation('sv', ['title' => 'Logga ut']);
        $link->addTranslation('fi', ['title' => 'Kirjaudu ulos']);
      }
      $link->save();
    }
  }
}
