<?php

use \Drupal\Core\Form\FormStateInterface;

/**
* Implements hook_form_alter().
*/
function uhsg_active_degree_programme_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_login_form') {
    $form['#submit'][] = '_uhsg_active_degree_programme_user_login_set_degree_programme';
  }
}
/**
* Submit handler for login form. Get degree programme reference from user and redirect to it.
*/
function _uhsg_active_degree_programme_user_login_set_degree_programme($form, FormStateInterface $form_state) {
  // TODO: get correct term id from user study rights
  $form_state->setRedirect('entity.taxonomy_term.canonical', array('taxonomy_term' => 16));
}
