# Schema for the configuration files of the oprek module.

uhsg_oprek.settings:
  type: config_object
  label: 'Oprek settings'
  mapping:
    base_url:
      type: string
      label: 'Endpoint base URL where all REST requests are sent to without trailing slash.'
    technical_condition_field_name:
      type: string
      label: 'Field name that indicates the flagging being programmatically managed.'
    primary_field_name:
      type: string
      label: 'Field name that indicates whether the degree programme is primary degree programme.'
    code_field_name:
      type: string
      label: 'Field name where code of degree programmes are.'
