<?php

/**
 * @file
 * Contains uhsg_degree_programme.module.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_query_alter().
 */
function uhsg_degree_programme_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  uhsg_degree_programme_alter_degree_programmes_query($view, $query);
}

/**
 * Remove langcode column join condition from degree programme type join query
 * in degree programmes view. We want to handle degree programme type as a
 * language neutral value (disregarding the UI language), so that the degree
 * programme type is present as a sorting filter for all languages (HUB-207).
 * Without this removal the degree programme grouping order will vary between
 * English and other languages, since the degree programme type is only stored
 * in English.
 */
function uhsg_degree_programme_alter_degree_programmes_query(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'degree_programmes') {

    /** @var $query \Drupal\views\Plugin\views\query\Sql */
    $table = $query->getTableInfo('taxonomy_term__field_degree_programme_type');

    if (isset($table['join']->extra[1]['left_field']) && $table['join']->extra[1]['left_field'] == 'langcode') {
      unset($table['join']->extra[1]);
    }
  }
}

/**
 * Implements hook_views_data().
 *
 * Provides a way to use the custom degree programme type sorting in views.
 */
function uhsg_degree_programme_views_data() {
  $data = [];
  $data['taxonomy_term__field_degree_programme_type']['degree_programme_type'] = [
    'title' => t('Custom degree programme type sort'),
    'group' => t('Taxonomy term'),
    'help' => t('Sort by degree programme type.'),
    'sort' => [
      'field' => 'field_degree_programme_type_value',
      'id' => 'degree_programme_type',
    ],
  ];
  return $data;
}
