<?php

/**
 * @file
 * Contains uhsg_degree_programme.module.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_views_post_execute().
 */
function uhsg_degree_programme_views_post_execute(ViewExecutable $view) {
  if ($view->id() == 'search') {

    $active_degree_programme_tid = \Drupal::service('uhsg_active_degree_programme.active_degree_programme')->getId();
    $degree_programme_fields = ['article_degree_programme_tid', 'news_degree_programme_tid'];
    $items_filtered_out = 0;

    /**
     * @var \Drupal\views\ResultRow $result
     */
    foreach ($view->result as $key => $result) {
      /**
       * @var \Drupal\search_api\Item\Item $result->_item
       */
      foreach ($degree_programme_fields as $degree_programme_field) {
        if (!empty($result->_item->getFields()[$degree_programme_field]->getValues())) {
          if (!in_array($active_degree_programme_tid, $result->_item->getFields()[$degree_programme_field]->getValues())) {
            // Filter result row item, if content has no active degree programme
            // selected.
            unset($view->result[$key]);
            $items_filtered_out++;
          }
        }
      }
    }
    $view->total_rows = $view->total_rows - $items_filtered_out;

  }
}

/**
 * Implements hook_views_query_alter().
 */
function uhsg_degree_programme_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  uhsg_degree_programme_alter_degree_programmes_query($view, $query);
}

/**
 * Remove langcode column join condition from degree programme type join query
 * in degree programmes view. We want to handle degree programme type as a
 * language neutral value (disregarding the UI language), so that the degree
 * programme type is present as a sorting filter for all languages (HUB-207).
 * Without this removal the degree programme grouping order will vary between
 * English and other languages, since the degree programme type is only stored
 * in English.
 */
function uhsg_degree_programme_alter_degree_programmes_query(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'degree_programmes') {

    /** @var $query \Drupal\views\Plugin\views\query\Sql */
    $table = $query->getTableInfo('taxonomy_term__field_degree_programme_type');

    if (isset($table['join']->extra[1]['left_field']) && $table['join']->extra[1]['left_field'] == 'langcode') {
      unset($table['join']->extra[1]);
    }
  }
}
