<?php

/**
 * Implements hook_page_attachments().
 */
function uhsg_cookie_consent_page_attachments(array &$page) {
  // Show cookie consent bar only for anonymous users and on teaching
  // instructions. Student guide will show a consent bar through obar. 
  $is_anonymous = \Drupal::currentUser()->isAnonymous();
  $is_teaching_domain = $is_anonymous && \Drupal::service('uhsg_domain.domain')->isTeachingDomain();

  if ($is_anonymous && $is_teaching_domain) {
    $page['#attached']['library'][] = 'uhsg_cookie_consent/uhsg-cookie-consent';
    $page['#attached']['library'][] = 'uhsg_cookie_consent/cookieconsent2';
    $page['#attached']['drupalSettings']['uhsg_cookie_consent']['options'] = [
      'domain' => \Drupal::config('uhsg_cookie_consent.config')->get('domain'),
      'message' => \Drupal::config('uhsg_cookie_consent.config')->get('message'),
      'learnMore' => \Drupal::config('uhsg_cookie_consent.config')->get('learnmore'),
      'dismiss' => \Drupal::config('uhsg_cookie_consent.config')->get('dismiss'),
      'link' => \Drupal::config('uhsg_cookie_consent.config')->get('link'),
      'theme' => \Drupal::config('uhsg_cookie_consent.config')->get('theme'),
    ];
  }
}
