<?php

/**
 * @file
 * Contains uhsg_article.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uhsg_article_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the uhsg_article module.
    case 'help.page.uhsg_article':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides article paragraphs.') . '</p>';
      return $output;

    default:
  }
}
