<?php

/**
 * Implements hook_views_pre_render().
 * Top content view has sitename in each result because of GA, remove that.
 */
function uhsg_top_content_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'google_analytics_summary' && $view->current_display == 'top_searches_block') {
    foreach ($view->result as &$result) {
      $pageTitleParts = explode('|', $result->pageTitle);
      $result->pageTitle = !empty($pageTitleParts[0]) ? $pageTitleParts[0] : $result->pageTitle;
    }
  }
}

/**
 * Implements hook_views_query_alter().
 *
 * Alter the Google Analytics Reports query for the by using the overridden profile ID
 * defined in settings.php
 */
function uhsg_top_content_views_query_alter(\Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\QueryPluginBase $query) {
  if ($view->id() == 'google_analytics_summary' && $view->current_display == 'top_searches_block') {
    $config = \Drupal::configFactory()->get('google_analytics_reports_api.settings');
    $query->options['profile_id'] = $config->get('profile_id');
  }
}
