
<?php

/**
 * Implements hook_views_pre_render().
 * Top content view has sitename in each result because of GA, remove that.
 */
function uhsg_top_content_views_pre_render(\Drupal\views\ViewExecutable $view) {
  if ($view->id() == 'google_analytics_summary' && $view->current_display == 'top_searches_block') {
    foreach ($view->result as &$result) {
      $pageTitleParts = explode('|', $result->pageTitle);
      $result->pageTitle = !empty($pageTitleParts[0]) ? $pageTitleParts[0] : $result->pageTitle;
    }
  }
}
