<?php

/**
 * Load and save 100 published article nodes that do not have a domain assigned
 * to trigger the automatic domain assignment.
 */
function uhsg_domain_install() {
  $nids = \Drupal::entityQuery('node')
    ->condition('type', 'article')
    ->condition('status', 1)
    ->notExists('field_article_domain')
    ->range(0, 100)
    ->execute();

  $nodes = \Drupal\node\Entity\Node::loadMultiple($nids);

  foreach ($nodes as $node) {
    $node->save();
  }
}
