# Schema for the configuration files of the degree programme module.

uhsg_degree_programme.settings:
  type: config_object
  label: 'Degree Programme settings'
  mapping:
    technical_condition_field_name:
      type: string
      label: 'Field name that indicates the flagging being programmatically managed.'
