<?php

/**
 * @file
 * Implementation for Student Guide Migrate module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function uhsg_migrate_migration_plugins_alter(&$definitions) {
  foreach ($definitions as $migration => $definition) {
    if ($definitions[$migration]['source']['plugin'] == 'csv') {
      $definitions[$migration]['source']['path'] = drupal_get_path('module', 'uhsg_migrate') . $definitions[$migration]['source']['path'];
    }
  }
}
