<?php

/**
 * @file
 * Implementation for Student Guide Migrate module.
 */

/**
 * Implements hook_migration_plugins_alter().
 */
function uhsg_migrate_migration_plugins_alter(&$definitions) {
  foreach (['some_links', 'degree_programmes'] as $migration) {
    $definitions[$migration]['source']['path'] = drupal_get_path('module', 'uhsg_migrate') . $definitions[$migration]['source']['path'];
  }
}
