<?php

/**
 * @file
 * Contains uhsg_feedback.module.
 */

 use Drupal\Core\Url;

/**
 * Implements hook_mail_alter().
 *
 * Modifies the feedback/contact email contents according to business
 * requirements.
 */
function uhsg_feedback_mail_alter(&$message) {

  // Restrict alteration to contact mail.
  if ($message['id'] == 'contact_page_mail') {

    // Contact message.
    $contact_message = $message['params']['contact_message'];

    // Do not send probable spam.
    if (uhsg_feedback_is_probably_spam($contact_message->get('message')->value)) {
      \Drupal::logger('uhsg_feedback')->debug('Detected probable spam. Preventing send.');
      $message['send'] = FALSE;
    }

    $replyTo = $message['reply-to'];

    // From: Either the email of the sender or the site default.
    if (!empty($replyTo)) {
      $message['from'] = $replyTo;
      $message['headers']['From'] = $replyTo;
    }

    // Reply-to: Either the email of the sender, or noreply@helsinki.fi.
    $noReply = 'noreply@helsinki.fi';
    $message['headers']['Reply-to'] = empty($replyTo) ? $noReply : $replyTo;

    // Reset to empty body.
    $message['body'] = [];

    // Subject.
    if (\Drupal::service('uhsg_domain.domain')->isTeachingDomain()) {
      $message['subject'] = t('Feedback from Instructions for teaching');
    }
    else {
      $message['subject'] = t('Feedback from Instructions for students');
    }

    // Date and time.
    $message['body'][] = date('d.m.Y H:i:s');

    // Message.
    $message['body'][] = $contact_message->get('message')->value;

    // I would like to get a response to my feedback.
    if ($contact_message->get('field_feedback_respond')->value) {
      $message['body'][] = t('I would like to get a response to my feedback: @replyTo', ['@replyto' => $replyTo]);
    }

    // Current page URL.
    $message['body'][] = Url::fromRoute('<current>', [], ['absolute' => TRUE])->toString();

    // User agent info.
    $message['body'][] = $_SERVER['HTTP_USER_AGENT'];
  }
}

/**
 * Try to detect possible spam. The message is considered spam if it contains
 * an URL and The URL does not include "helsinki.fi". The URL detection regular
 * expression is @gruber v2 from https://mathiasbynens.be/demo/url-regex
 *
 * @param string $message Message
 * @return bool TRUE if probably spam, otherwise FALSE.
 */
function uhsg_feedback_is_probably_spam($message) {
  $pattern = "#(?i)\b((?:[a-z][\w-]+:(?:/{1,3}|[a-z0-9%])|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))#iS";
  $matches = [];
  preg_match($pattern, $message, $matches);

  return !empty($matches[0]) && strpos($matches[0], 'helsinki.fi') === FALSE;
}

/**
 * Implements hook_form_alter().
 *
 * Hide preview and message field label from feedback form.
 */
function uhsg_feedback_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'contact_message_feedback_form_form') {
    $form['message']['widget'][0]['value']['#title_display'] = 'invisible';
    $form['message']['widget'][0]['value']['#placeholder'] = t('Give feedback about the service...');
    $form['mail']['#required'] = FALSE;
    $form['actions']['preview']['#access'] = FALSE;
    $form['actions']['submit']['#value'] = t('Send feedback');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 *
 * Feedback form hidden by default.
 */
function uhsg_feedback_preprocess_form(&$variables) {
  if ($variables['element']['#form_id'] == 'contact_message_feedback_form_form') {
    $variables['attributes']['class'][] = 'visually-hidden';
  }
}

/**
 * Implements hook_theme().
 */
function uhsg_feedback_theme($existing, $type, $theme, $path) {
  return [
    'block__contact_block' => [
      'template' => 'block--contact-block',
      'base hook' => 'block',
    ],
  ];
}
