<?php

/**
 * @file
 * Contains uhsg_feedback.module.
 */

/**
 * Implements hook_mail_alter().
 *
 * Modifies the feedback/contact email contents according to business
 * requirements.
 */
function uhsg_feedback_mail_alter(&$message) {

  // Restrict alteration to contact mail.
  if ($message['id'] == 'contact_page_mail') {

    // Reply-to: Either the email of the sender, or noreply@helsinki.fi.
    $noReply = 'noreply@helsinki.fi';
    $message['headers']['Reply-to'] = empty($message['reply-to']) ? $noReply : $message['reply-to'];

    // Reset to empty body.
    $message['body'] = [];

    // Subject.
    $message['subject'] = t('Feedback from Student Guide');

    // Date and time.
    $message['body'][] = date('d.m.Y H:i:s');

    // Message.
    $contact_message = $message['params']['contact_message'];
    $message['body'][] = $contact_message->get('message')->value;

    // I would like to get a response to my feedback.
    if ($contact_message->get('field_feedback_respond')->value) {
      $message['body'][] = t('I would like to get a response to my feedback') . ': ' . $message['reply-to'];
    }

    // Current page URL.
    $message['body'][] = \Drupal\Core\Url::fromRoute('<current>', [], ['absolute' => TRUE])->toString();

    // User agent info.
    $message['body'][] = $_SERVER['HTTP_USER_AGENT'];
  }
}
