<?php

/**
 * @file
 * Contains uhsg_feedback.module.
 */

/**
 * Implements hook_mail_alter().
 *
 * Modifies the feedback/contact email contents according to business
 * requirements.
 */
function uhsg_feedback_mail_alter(&$message) {

  // Restrict alteration to contact mail.
  if ($message['id'] == 'contact_page_mail') {

    $replyTo = $message['reply-to'];

    // From: Either the email of the sender or the site default.
    if (!empty($replyTo)) {
      $message['from'] = $replyTo;
      $message['headers']['From'] = $replyTo;
    }

    // Reply-to: Either the email of the sender, or noreply@helsinki.fi.
    $noReply = 'noreply@helsinki.fi';
    $message['headers']['Reply-to'] = empty($replyTo) ? $noReply : $replyTo;

    // Reset to empty body.
    $message['body'] = [];

    // Subject.
    $message['subject'] = t('Feedback from Student Guide');

    // Date and time.
    $message['body'][] = date('d.m.Y H:i:s');

    // Message.
    $contact_message = $message['params']['contact_message'];
    $message['body'][] = $contact_message->get('message')->value;

    // I would like to get a response to my feedback.
    if ($contact_message->get('field_feedback_respond')->value) {
      $message['body'][] = t('I would like to get a response to my feedback') . ': ' . $replyTo;
    }

    // Current page URL.
    $message['body'][] = \Drupal\Core\Url::fromRoute('<current>', [], ['absolute' => TRUE])->toString();

    // User agent info.
    $message['body'][] = $_SERVER['HTTP_USER_AGENT'];
  }
}

/**
 * Implements hook_form_alter().
 * Hide preview and message field label from feedback form.
 */
function uhsg_feedback_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'contact_message_feedback_form_form') {
    $form['message']['widget'][0]['value']['#title_display'] = 'visually-hidden';
    $form['message']['widget'][0]['value']['#placeholder'] = t('Give feedback about the service...');
    $form['mail']['#required'] = FALSE;
    $form['actions']['preview']['#access'] = FALSE;
    $form['actions']['submit']['#value'] = t('Send feedback');
  }
}

/**
 * Implements hook_preprocess_HOOK().
 * Feedback form hidden by default.
 */
function uhsg_feedback_preprocess_form(&$variables) {
  if ($variables['element']['#form_id'] == 'contact_message_feedback_form_form') {
    $variables['attributes']['class'][] = 'visually-hidden';
  }
}

/**
 * Implements hook_theme().
 */
function uhsg_feedback_theme($existing, $type, $theme, $path) {
  return array(
    'block__contact_block' => array(
      'template' => 'block--contact-block',
      'base hook' => 'block',
    )
  );
}
