<?php

/**
 * Implements hook_preprocess_hook().
 */
function uhsg_obar_preprocess_region(&$variables) {
  if ($variables['region'] == 'header') {
    $config = \Drupal::config('uhsg_obar');
    $variables['obar_base_url'] = $config->get('base_url');
    $variables['obar_app_name'] = $config->get('app_name');
    $variables['obar_jwt_token'] = \Drupal::service('uhsg_obar.jwt')->generateToken();
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function uhsg_obar_theme_suggestions_region_alter(&$suggestions, $variables, $hook) {
  if ($variables['elements']['#region'] == 'header') {
    if (\Drupal::service('uhsg_domain.domain')->isStudentDomain()) {
      array_push($suggestions, 'region__header__obar');
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function uhsg_obar_page_attachments_alter(&$page) {
  $page['#attached']['drupalSettings']['uhsgObar']['obarBaseUrl'] = \Drupal::config('uhsg_obar.settings')->get('obar_base_url');
}
