<?php

/**
 * Implements hook_preprocess_hook().
 */
function uhsg_obar_preprocess_region(&$variables) {
  if ($variables['region'] == 'header') {
    // TODO
    $variables['obar_base_url'] = '';
    $variables['obar_app_name'] = '';
    $variables['obar_jwt_token'] = '';
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function uhsg_obar_theme_suggestions_region_alter(&$suggestions, $variables, $hook) {
  if ($variables['elements']['#region'] == 'header') {
    if (\Drupal::service('uhsg_domain.domain')->isStudentDomain()) {
      array_push($suggestions, 'region__header__obar');
    }
  }
}
