<?php

/**
 * Implements hook_library_info_build().
 */
function uhsg_obar_library_info_build() {
  $libraries = [];
  $libraries['uhsg_obar.obar'] = [
    'js' => [
      'js/obar.js' => [],
    ],
    'css' => [
      'base' => [
        \Drupal::config('uhsg_obar.settings')->get('base_url') . '/obar.css' => ['type' => 'external'],
      ],
    ],
    'dependencies' => [
      'core/jquery',
      'core/drupalSettings',
    ],
  ];
  return $libraries;
}

/**
 * Implements hook_preprocess_hook().
 */
function uhsg_obar_preprocess_region(&$variables) {
  if ($variables['region'] == 'header' && \Drupal::service('uhsg_domain.domain')->isStudentDomain()) {
    $config = \Drupal::config('uhsg_obar.settings');
    $variables['obar_base_url'] = $config->get('base_url');
    $variables['obar_app_name'] = $config->get('app_name');
    $variables['obar_jwt_token'] = \Drupal::service('uhsg_obar.jwt')->generateToken();
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function uhsg_obar_theme_suggestions_region_alter(&$suggestions, $variables, $hook) {
  if ($variables['elements']['#region'] == 'header') {
    if (\Drupal::service('uhsg_domain.domain')->isStudentDomain()) {
      array_push($suggestions, 'region__header__obar');
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function uhsg_obar_page_attachments_alter(&$page) {
  if (\Drupal::service('uhsg_domain.domain')->isStudentDomain()) {
    $page['#attached']['drupalSettings']['uhsgObar']['obarBaseUrl'] = \Drupal::config('uhsg_obar.settings')->get('base_url');
    $page['#attached']['library'][] = 'uhsg_obar/uhsg_obar.obar';
  }
}
