# Schema for the configuration files of the cookie consent module.

uhsg_cookie_consent.config:
  type: config_object
  label: 'Cookie consent settings'
  mapping:
    link_path:
      type: text
      label: 'Learn more link path'

