<?php

/**
 * Implements hook_preprocess_HOOK().
 *
 * Add an id attribute to each paragraph for linking to it from the table of
 * contents. Handle Eduviewer paragraph type.
 */
function uhsg_eduviewer_preprocess_paragraph(&$variables) {
  $variables['attributes']['id'] = 'paragraph-' . $variables['paragraph']->id();

  if ($variables['paragraph']->getType() == 'eduviewer') {

    /** @var $active_degree_programme_service \Drupal\uhsg_active_degree_programme\ActiveDegreeProgrammeService */
    $active_degree_programme_service = \Drupal::service('uhsg_active_degree_programme.active_degree_programme');
    $active_degree_programme_code = $active_degree_programme_service->getCode();
    $eduviewer_script_src =  \Drupal::config('uhsg_eduviewer.config')->get('script_src');

    if (!empty($active_degree_programme_code) && !empty($eduviewer_script_src)) {
      $language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $eduviewer_markup = "<div id=\"eduviewer-root\" degree-program-id=\"$active_degree_programme_code\" lang=\"$language\" ></div>";

      $variables['eduviewer'] = [
        '#markup' => $eduviewer_markup,
        '#script_src' => $eduviewer_script_src
      ];

      $variables['attributes']['class'][] = 'eduviewer';
      $variables['#cache']['max-age'] = 0;
      $variables['#cache']['contexts'][] = 'active_degree_programme';
      $variables['#cache']['contexts'][] = 'languages:language_interface';
    }
  }
}
