# Schema for the configuration files of the user sync module.

uhsg_user_sync.settings:
  type: config_object
  label: 'User Sync settings'
  mapping:
    studentID_field_name:
      type: string
      label: 'Field name where student ID gets synchronised.'
