# Schema for the configuration files of the user sync module.

uhsg_user_sync.settings:
  type: config_object
  label: 'User Sync settings'
  mapping:
    code_field_name:
      type: string
      label: 'Field name where code of degree programmes are.'
    oodiUID_field_name:
      type: string
      label: 'Field name where Oodi UID gets synchronised.'
    primary_field_name:
      type: string
      label: 'Field name that indicates whether the degree programme is primary degree programme.'
    employeeID_field_name:
      type: string
      label: 'Field name where employee ID gets synchronised.'
    studentID_field_name:
      type: string
      label: 'Field name where student ID gets synchronised.'
    technical_condition_field_name:
      type: string
      label: 'Field name that indicates the flagging being programmatically managed.'
    common_name_field_name:
      type: string
      label: 'Field name for common name synchronization'
