<?php

/**
 * @file
 * Contains uhsg_themes.module.
 */

/**
 * Implements hook_preprocess_HOOK() for views.
 * Make theme view sortable.
 */
function uhsg_themes_preprocess_views_view(&$variables) {
  if ($variables['view']->id() == 'themes') {
    $variables['#attached']['library'][] = 'uhsg_themes/sortable';
    $variables['#attached']['library'][] = 'uhsg_themes/theme_sort';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * We would like to change the one paragraph field help text from 'No Paragraphs
 * added yet.' to something more helpful. See HUB-222.
 */
function uhsg_themes_form_node_theme_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if (!empty($form['field_theme_faq']['widget']['text']['value']['#markup'])) {
    /** @var \Drupal\Core\StringTranslation\TranslatableMarkup $markup */
    $markup = $form['field_theme_faq']['widget']['text']['value']['#markup'];
    if ($markup->getUntranslatedString() == 'No @title added yet.') {
      $form['field_theme_faq']['widget']['text']['value']['#markup'] = new \Drupal\Core\StringTranslation\TranslatableMarkup('Add FAQ section from original translation.');
    }
  }
}
